service:
  name: yang si-myung
  phone: "010-"
  sex: 'M'

spring:
  profiles:
    active: prod1,prod2

---
spring.profiles: prod1,prod2

db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//123.45.67.78:1521/prod
  user: prod
  password: prod1234

---
spring.profiles: test1,test2

db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//123.45.67.78:1521/dev
  user: devtest
  password: test

---
spring.profiles: staging
db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//123.45.67.78:1521/alpha
  user: alphatest
  password: test

---
spring.profiles: local

db:
  driver: org.h2.Driver
  url: jdbc:h2:mem:local;DB_CLOSE_DELAY=-1;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=2
  user: sa
  password: "123zzz"

